import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import { CounterStoreProvider } from '@/providers/counter-store-provider'
import { initCounterStore } from "@/stores/counter-store";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const state = initCounterStore()

  return (
    <html lang="en">
      <body className={inter.className}>
        <CounterStoreProvider initialState={state}>{children}</CounterStoreProvider>
      </body>
    </html>
  )
}
